name: Music Assistant BETA
version: 2.0.0b92
slug: music_assistant_beta
description: BETA version of Music Assistant. Install this version if you want to
  keep up with the latest and greatest and don't mind some beta testing. Follow us
  on discord to report and discuss feedback!
url: https://github.com/music-assistant/hass-music-assistant
arch:
- amd64
- aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
- media:rw
init: false
advanced: false
stage: stable
image: ghcr.io/music-assistant/server
tmpfs: true
ports:
  8095/tcp: 8095
ports_description:
  8095/tcp: Musicassistant server port (make empty to disable)
options:
  log_level: info
  enable_uvloop: false
schema:
  log_level: list(debug|info|warning|error)
  enable_uvloop: bool
privileged:
- SYS_ADMIN
- DAC_READ_SEARCH
